package magickwand

/*
#cgo LDFLAGS: -lMagickWand-Q16 -lMagickCore-Q16
#cgo CFLAGS: -fopenmp -I/usr/local/include/ImageMagick

#include <wand/magick_wand.h>
*/
import "C"

const (
	/* FilterTypes */
	BesselFilter   = int(C.BesselFilter)
	BlackmanFilter = int(C.BlackmanFilter)
	BoxFilter      = int(C.BoxFilter)
	CatromFilter   = int(C.CatromFilter)
	GaussianFilter = int(C.GaussianFilter)
	HanningFilter  = int(C.HanningFilter)
	HermiteFilter  = int(C.HermiteFilter)
	LanczosFilter  = int(C.LanczosFilter)
	MitchellFilter = int(C.MitchellFilter)
	SincFilter     = int(C.SincFilter)
	TriangleFilter = int(C.TriangleFilter)

	/* Compression */
	UndefinedCompression    = int(C.UndefinedCompression)
	NoCompression           = int(C.NoCompression)
	BZipCompression         = int(C.BZipCompression)
	DXT1Compression         = int(C.DXT1Compression)
	DXT3Compression         = int(C.DXT3Compression)
	DXT5Compression         = int(C.DXT5Compression)
	FaxCompression          = int(C.FaxCompression)
	Group4Compression       = int(C.Group4Compression)
	JPEGCompression         = int(C.JPEGCompression)
	JPEG2000Compression     = int(C.JPEG2000Compression)
	LosslessJPEGCompression = int(C.LosslessJPEGCompression)
	LZWCompression          = int(C.LZWCompression)
	RLECompression          = int(C.RLECompression)
	ZipCompression          = int(C.ZipCompression)
	ZipSCompression         = int(C.ZipSCompression)
	PizCompression          = int(C.PizCompression)
	Pxr24Compression        = int(C.Pxr24Compression)
	B44Compression          = int(C.B44Compression)
	B44ACompression         = int(C.B44ACompression)

	/* Composite */
	UndefinedCompositeOp       = int(C.UndefinedCompositeOp)
	NoCompositeOp              = int(C.NoCompositeOp)
	ModulusAddCompositeOp      = int(C.ModulusAddCompositeOp)
	AtopCompositeOp            = int(C.AtopCompositeOp)
	BlendCompositeOp           = int(C.BlendCompositeOp)
	BumpmapCompositeOp         = int(C.BumpmapCompositeOp)
	ChangeMaskCompositeOp      = int(C.ChangeMaskCompositeOp)
	ClearCompositeOp           = int(C.ClearCompositeOp)
	ColorBurnCompositeOp       = int(C.ColorBurnCompositeOp)
	ColorDodgeCompositeOp      = int(C.ColorDodgeCompositeOp)
	ColorizeCompositeOp        = int(C.ColorizeCompositeOp)
	CopyBlackCompositeOp       = int(C.CopyBlackCompositeOp)
	CopyBlueCompositeOp        = int(C.CopyBlueCompositeOp)
	CopyCompositeOp            = int(C.CopyCompositeOp)
	CopyCyanCompositeOp        = int(C.CopyCyanCompositeOp)
	CopyGreenCompositeOp       = int(C.CopyGreenCompositeOp)
	CopyMagentaCompositeOp     = int(C.CopyMagentaCompositeOp)
	CopyOpacityCompositeOp     = int(C.CopyOpacityCompositeOp)
	CopyRedCompositeOp         = int(C.CopyRedCompositeOp)
	CopyYellowCompositeOp      = int(C.CopyYellowCompositeOp)
	DarkenCompositeOp          = int(C.DarkenCompositeOp)
	DstAtopCompositeOp         = int(C.DstAtopCompositeOp)
	DstCompositeOp             = int(C.DstCompositeOp)
	DstInCompositeOp           = int(C.DstInCompositeOp)
	DstOutCompositeOp          = int(C.DstOutCompositeOp)
	DstOverCompositeOp         = int(C.DstOverCompositeOp)
	DifferenceCompositeOp      = int(C.DifferenceCompositeOp)
	DisplaceCompositeOp        = int(C.DisplaceCompositeOp)
	DissolveCompositeOp        = int(C.DissolveCompositeOp)
	ExclusionCompositeOp       = int(C.ExclusionCompositeOp)
	HardLightCompositeOp       = int(C.HardLightCompositeOp)
	HueCompositeOp             = int(C.HueCompositeOp)
	InCompositeOp              = int(C.InCompositeOp)
	LightenCompositeOp         = int(C.LightenCompositeOp)
	LinearLightCompositeOp     = int(C.LinearLightCompositeOp)
	LuminizeCompositeOp        = int(C.LuminizeCompositeOp)
	MinusDstCompositeOp        = int(C.MinusDstCompositeOp)
	ModulateCompositeOp        = int(C.ModulateCompositeOp)
	MultiplyCompositeOp        = int(C.MultiplyCompositeOp)
	OutCompositeOp             = int(C.OutCompositeOp)
	OverCompositeOp            = int(C.OverCompositeOp)
	OverlayCompositeOp         = int(C.OverlayCompositeOp)
	PlusCompositeOp            = int(C.PlusCompositeOp)
	ReplaceCompositeOp         = int(C.ReplaceCompositeOp)
	SaturateCompositeOp        = int(C.SaturateCompositeOp)
	ScreenCompositeOp          = int(C.ScreenCompositeOp)
	SoftLightCompositeOp       = int(C.SoftLightCompositeOp)
	SrcAtopCompositeOp         = int(C.SrcAtopCompositeOp)
	SrcCompositeOp             = int(C.SrcCompositeOp)
	SrcInCompositeOp           = int(C.SrcInCompositeOp)
	SrcOutCompositeOp          = int(C.SrcOutCompositeOp)
	SrcOverCompositeOp         = int(C.SrcOverCompositeOp)
	ModulusSubtractCompositeOp = int(C.ModulusSubtractCompositeOp)
	ThresholdCompositeOp       = int(C.ThresholdCompositeOp)
	XorCompositeOp             = int(C.XorCompositeOp)
	/* new add */
	DivideDstCompositeOp        = int(C.DivideDstCompositeOp)
	DistortCompositeOp          = int(C.DistortCompositeOp)
	BlurCompositeOp             = int(C.BlurCompositeOp)
	PegtopLightCompositeOp      = int(C.PegtopLightCompositeOp)
	VividLightCompositeOp       = int(C.VividLightCompositeOp)
	PinLightCompositeOp         = int(C.PinLightCompositeOp)
	LinearDodgeCompositeOp      = int(C.LinearDodgeCompositeOp)
	LinearBurnCompositeOp       = int(C.LinearBurnCompositeOp)
	MathematicsCompositeOp      = int(C.MathematicsCompositeOp)
	DivideSrcCompositeOp        = int(C.DivideSrcCompositeOp)
	MinusSrcCompositeOp         = int(C.MinusSrcCompositeOp)
	DarkenIntensityCompositeOp  = int(C.DarkenIntensityCompositeOp)
	LightenIntensityCompositeOp = int(C.LightenIntensityCompositeOp)

	// exception
	UndefinedException        = 0
	WarningException          = 300
	ResourceLimitWarning      = 300
	TypeWarning               = 305
	OptionWarning             = 310
	DelegateWarning           = 315
	MissingDelegateWarning    = 320
	CorruptImageWarning       = 325
	FileOpenWarning           = 330
	BlobWarning               = 335
	StreamWarning             = 340
	CacheWarning              = 345
	CoderWarning              = 350
	FilterWarning             = 352
	ModuleWarning             = 355
	DrawWarning               = 360
	ImageWarning              = 365
	WandWarning               = 370
	RandomWarning             = 375
	XServerWarning            = 380
	MonitorWarning            = 385
	RegistryWarning           = 390
	ConfigureWarning          = 395
	PolicyWarning             = 399
	ErrorException            = 400
	ResourceLimitError        = 400
	TypeError                 = 405
	OptionError               = 410
	DelegateError             = 415
	MissingDelegateError      = 420
	CorruptImageError         = 425
	FileOpenError             = 430
	BlobError                 = 435
	StreamError               = 440
	CacheError                = 445
	CoderError                = 450
	FilterError               = 452
	ModuleError               = 455
	DrawError                 = 460
	ImageError                = 465
	WandError                 = 470
	RandomError               = 475
	XServerError              = 480
	MonitorError              = 485
	RegistryError             = 490
	ConfigureError            = 495
	PolicyError               = 499
	FatalErrorException       = 700
	ResourceLimitFatalError   = 700
	TypeFatalError            = 705
	OptionFatalError          = 710
	DelegateFatalError        = 715
	MissingDelegateFatalError = 720
	CorruptImageFatalError    = 725
	FileOpenFatalError        = 730
	BlobFatalError            = 735
	StreamFatalError          = 740
	CacheFatalError           = 745
	CoderFatalError           = 750
	FilterFatalError          = 752
	ModuleFatalError          = 755
	DrawFatalError            = 760
	ImageFatalError           = 765
	WandFatalError            = 770
	RandomFatalError          = 775
	XServerFatalError         = 780
	MonitorFatalError         = 785
	RegistryFatalError        = 790
	ConfigureFatalError       = 795
	PolicyFatalError          = 79
)
